name: Pipeline
on: [push, pull_request]


jobs:
  test:
    runs-on:  ubuntu-latest

    env:
      DATABASE_URL: ${{secrets.DATABASE_URL }}
      SECRET_KEY: ${{secrets.SECRET_KEY }}

      ALGORITHM: ${{secrets.ALGORITHM }}

      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
      - name: copia os arquivos do repo
        uses: actions/checkout@v3
      - name: instalar o python
        uses: actions/setup-python@v5

        with:
          python-version: '3.12.7'

      - name: instalar o poetry
        run: pipx install poetry

      - name: instalando dependencias
        run: poetry install


      - name: Executar testes
        run: poetry run task test
